"""add vault external_path

Revision ID: 7eb4f5f4da10
Revises: 82ba996daa2a
Create Date: 2026-08-20 04:46:50.656631
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '7eb4f5f4da10'
down_revision = '82ba996daa2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaults', sa.Column('external_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'external_path')
    # ### end Alembic commands ###
