"""add ai_config, ai_actions

Revision ID: 82ba996daa2a
Revises: 5784909a52d1
Create Date: 2026-08-19 13:28:46.745702
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '82ba996daa2a'
down_revision = '5784909a52d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('tool_input', sa.JSON(), nullable=False),
    sa.Column('safety', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('auto_approve_safe', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_config')
    op.drop_table('ai_actions')
    # ### end Alembic commands ###
