"""add obsidian rest connection

Revision ID: 912a0739ff9a
Revises: 7eb4f5f4da10
Create Date: 2026-08-20 04:53:25.663823
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '912a0739ff9a'
down_revision = '7eb4f5f4da10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obsidian_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('use_https', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obsidian_connections')
    # ### end Alembic commands ###
