"""initial schema

Revision ID: ae913ac934e4
Revises: 
Create Date: 2026-08-18 18:24:17.282665
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ae913ac934e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaults',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('note_path', sa.String(length=1024), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault_settings')
    op.drop_table('templates')
    op.drop_table('plugins')
    op.drop_table('activities')
    op.drop_table('vaults')
    # ### end Alembic commands ###
