import { useMemo } from 'react'
import ReactMarkdown, { defaultUrlTransform } from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { transformWikilinks, isWikilinkHref, targetFromHref, WIKILINK_SCHEME } from '@/lib/wikilink'
import { resolveLinkTarget, flattenFiles } from '@/lib/tree'
import { useVaultStore } from '@/store/vaultStore'

// react-markdown strips hrefs with URL schemes it doesn't recognize as safe
// (http/https/mailto/...), which silently blanked out every wikilink:// href
// generated by transformWikilinks. Keep the default sanitizer for genuine
// links but allowlist our own internal scheme.
function urlTransform(url: string): string {
  return url.startsWith(WIKILINK_SCHEME) ? url : defaultUrlTransform(url)
}

interface Props {
  content: string
  onOpenNote: (path: string) => void
  onCreateNote: (path: string) => void
}

export function MarkdownPreview({ content, onOpenNote, onCreateNote }: Props) {
  const tree = useVaultStore((s) => s.tree)
  const files = useMemo(() => flattenFiles(tree), [tree])
  const transformed = useMemo(() => transformWikilinks(content), [content])

  return (
    <div className="markdown-body px-8 py-6 max-w-[820px] mx-auto">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        urlTransform={urlTransform}
        components={{
          a: ({ href, children, ...rest }) => {
            if (href && isWikilinkHref(href)) {
              const target = targetFromHref(href)
              const resolved = resolveLinkTarget(files, target)
              if (resolved) {
                return (
                  <a
                    className="wikilink"
                    onClick={(e) => {
                      e.preventDefault()
                      onOpenNote(resolved)
                    }}
                    href="#"
                  >
                    {children}
                  </a>
                )
              }
              return (
                <a
                  className="wikilink wikilink-unresolved"
                  title={`Create "${target}"`}
                  onClick={(e) => {
                    e.preventDefault()
                    onCreateNote(target)
                  }}
                  href="#"
                >
                  {children}
                </a>
              )
            }
            return (
              <a href={href} target="_blank" rel="noreferrer" {...rest}>
                {children}
              </a>
            )
          },
        }}
      >
        {transformed}
      </ReactMarkdown>
    </div>
  )
}
